export const FETCH_ALBUM_REQUEST = "FETCH_ALBUM_REQUEST";
export const FETCH_ALBUM_SUCCESS = "FETCH_ALBUM_SUCCESS";
export const FETCH_ALBUM_FAILURE = "FETCH_ALBUM_FAILURE";

export const FETCH_DETAILED_ALBUM_REQUEST = "FETCH_DETAILED_ALBUM_REQUEST";
export const FETCH_DETAILED_ALBUM_SUCCESS = "FETCH_DETAILED_ALBUM_SUCCESS";
export const FETCH_DETAILED_ALBUM_FAILURE = "FETCH_DETAILED_ALBUM_FAILURE";
