// Get artist
export const FETCH_ARTIST_REQUEST = "FETCH_ARTIST_REQUEST";
export const FETCH_ARTIST_SUCCESS = "FETCH_ARTIST_SUCCESS";
export const FETCH_ARTIST_FAILURE = "FETCH_ARTIST_FAILURE";

// Get artist's toptracks
export const FETCH_ARTIST_TOPTRACK_REQUEST = "FETCH_ARTIST_TOPTRACK_REQUEST";
export const FETCH_ARTIST_TOPTRACK_SUCCESS = "FETCH_ARTIST_TOPTRACK_SUCCESS";
export const FETCH_ARTIST_TOPTRACK_FAILURE = "FETCH_ARTIST_TOPTRACK_FAILURE";
// Get artist's albums
export const FETCH_ARTIST_ALBUMS_REQUEST = "FETCH_ARTIST_ALBUMS_REQUEST";
export const FETCH_ARTIST_ALBUMS_SUCCESS = "FETCH_ARTIST_ALBUMS_SUCCESS";
export const FETCH_ARTIST_ALBUMS_FAILURE = "FETCH_ARTIST_ALBUMS_FAILURE";
// Get artist's related artists
export const FETCH_ARTIST_RELATED_REQUEST = "FETCH_ARTIST_RELATED_REQUEST";
export const FETCH_ARTIST_RELATED_SUCCESS = "FETCH_ARTIST_RELATED_SUCCESS";
export const FETCH_ARTIST_RELATED_FAILURE = "FETCH_ARTIST_RELATED_FAILURE";
