export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";


export const FETCH_CATEGORY_PLAYLIST_REQUEST = "FETCH_CATEGORY_PLAYLIST_REQUEST";
export const FETCH_CATEGORY_PLAYLIST_SUCCESS = "FETCH_CATEGORY_PLAYLIST_SUCCESS";
export const FETCH_CATEGORY_PLAYLIST_FAILURE = "FETCH_CATEGORY_PLAYLIST_FAILURE";