export const FETCH_RECOMMENDATION_REQUEST = "FETCH_RECOMMENDATION_REQUEST";
export const FETCH_RECOMMENDATION_SUCCESS = "FETCH_RECOMMENDATION_SUCCESS";
export const FETCH_RECOMMENDATION_FAILURE = "FETCH_RECOMMENDATION_FAILURE";
